In [ ]:

# Complete ML Workflow Example: Yield Prediction

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# === STEP 1: DEFINE PROBLEM ===
print("=== Step 1: Problem Definition ===")
print("Goal: Predict crop yield based on input factors")
print("Type: Regression (predicting continuous value)")

# === STEP 2: COLLECT DATA ===
print("\n=== Step 2: Data Collection ===")
np.random.seed(42)
n_samples = 100

data = pd.DataFrame({
    'rainfall': np.random.uniform(100, 400, n_samples),
    'temperature': np.random.uniform(20, 35, n_samples),
    'fertilizer': np.random.uniform(30, 100, n_samples),
    'soil_ph': np.random.uniform(5.5, 7.5, n_samples),
})

# Generate yield based on factors (with noise)
data['yield'] = (
    10 * data['rainfall'] +
    -50 * data['temperature'] +
    15 * data['fertilizer'] +
    200 * data['soil_ph'] +
    np.random.normal(0, 100, n_samples)
)
print(f"Dataset shape: {data.shape}")
print(data.head())

# === STEP 3: PREPARE DATA ===
print("\n=== Step 3: Data Preparation ===")
X = data[['rainfall', 'temperature', 'fertilizer', 'soil_ph']]
y = data['yield']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

# === STEP 4: TRAIN MODEL ===
print("\n=== Step 4: Model Training ===")
model = LinearRegression()
model.fit(X_train, y_train)
print("Model trained successfully!")

# === STEP 5: EVALUATE ===
print("\n=== Step 5: Evaluation ===")
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f} kg")
print(f"R² Score: {r2:.4f}")

# === STEP 6: USE MODEL ===
print("\n=== Step 6: Make Predictions ===")
new_field = [[250, 28, 60, 6.5]]  # New field data
prediction = model.predict(new_field)
print(f"Predicted yield for new field: {prediction[0]:.0f} kg/ha")


=== Step 1: Problem Definition ===
Goal: Predict crop yield based on input factors
Type: Regression (predicting continuous value)

=== Step 2: Data Collection ===
Dataset shape: (100, 5)
     rainfall  temperature  fertilizer   soil_ph        yield
0  212.362036    20.471438   74.942215  5.603363  3475.402265
1  385.214292    29.546156   35.889798  6.562709  4227.824311
2  319.598183    24.715340   41.314010  6.581270  3964.374335
3  279.597545    27.628560   92.898793  6.774860  4131.974617
4  146.805592    33.613497   72.450034  6.952183  2296.984747

=== Step 3: Data Preparation ===
Training samples: 80
Testing samples: 20

=== Step 4: Model Training ===
Model trained successfully!

=== Step 5: Evaluation ===
RMSE: 97.06 kg
R² Score: 0.9924

=== Step 6: Make Predictions ===
Predicted yield for new field: 3304 kg/ha


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [4]:

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# === SIMPLE LINEAR REGRESSION ===
print("=== Simple Linear Regression ===")
print("Predicting yield from fertilizer only")

# Data
fertilizer = np.array([20, 30, 40, 50, 60, 70, 80, 90, 100]).reshape(-1, 1)
yield_kg = np.array([1800, 2100, 2400, 2650, 2850, 3000, 3100, 3150, 3180])

# Train model
model = LinearRegression()
model.fit(fertilizer, yield_kg)

print(f"Intercept (base yield): {model.intercept_:.0f} kg")
print(f"Coefficient: {model.coef_[0]:.1f} kg per kg fertilizer")
print(f"Interpretation: Each kg of fertilizer adds {model.coef_[0]:.1f} kg yield")

# Predict
new_fert = [[55]]
pred = model.predict(new_fert)
print(f"\nPredicted yield at 55kg fertilizer: {pred[0]:.0f} kg")

# === MULTIPLE LINEAR REGRESSION ===
print("\n=== Multiple Linear Regression ===")

# Multiple features
data = pd.DataFrame({
    'rainfall': [150, 200, 180, 250, 300, 190, 220, 280],
    'fertilizer': [40, 50, 45, 60, 70, 55, 65, 75],
    'temperature': [28, 30, 29, 27, 26, 28, 27, 25],
    'yield': [2200, 2600, 2400, 2900, 3200, 2700, 2850, 3100]
})

X = data[['rainfall', 'fertilizer', 'temperature']]
y = data['yield']

model_multi = LinearRegression()
model_multi.fit(X, y)

print("Feature Importance (Coefficients):")
for feature, coef in zip(X.columns, model_multi.coef_):
    print(f"  {feature}: {coef:.2f}")

# Predict for new conditions
new_conditions = [[230, 58, 27]]
prediction = model_multi.predict(new_conditions)
print(f"\nPredicted yield: {prediction[0]:.0f} kg/ha")


=== Simple Linear Regression ===
Predicting yield from fertilizer only
Intercept (base yield): 1650 kg
Coefficient: 17.4 kg per kg fertilizer
Interpretation: Each kg of fertilizer adds 17.4 kg yield

Predicted yield at 55kg fertilizer: 2605 kg

=== Multiple Linear Regression ===
Feature Importance (Coefficients):
  rainfall: 3.26
  fertilizer: 18.21
  temperature: 37.21

Predicted yield: 2763 kg/ha


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# === SIMPLE LINEAR REGRESSION ===
print("=== Simple Linear Regression ===")
fertilizer = np.array([20, 30, 40, 50, 60, 70, 80, 90, 100]).reshape(-1, 1)
yield_kg = np.array([1800, 2100, 2400, 2650, 2850, 3000, 3100, 3150, 3180])

# Scale features
scaler = StandardScaler()
fertilizer_scaled = scaler.fit_transform(fertilizer)

#

=== Simple Linear Regression ===


In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# === SIMPLE LINEAR REGRESSION ===
print("=== Simple Linear Regression ===")
fertilizer = np.array([20, 30, 40, 50, 60, 70, 80, 90, 100]).reshape(-1, 1)
yield_kg = np.array([1800, 2100, 2400, 2650, 2850, 3000, 3100, 3150, 3180])

# Scale features
scaler = StandardScaler()
fertilizer_scaled = scaler.fit_transform(fertilizer)

# Train model with Ridge regularization
model = RidgeCV(cv=3)
model.fit(fertilizer_scaled, yield_kg)
print(f"Best alpha: {model.alpha_}")

# Predict
new_fert = [[55]]
new_fert_scaled = scaler.transform(new_fert)
pred = model.predict(new_fert_scaled)
print(f"Predicted yield at 55kg fertilizer: {pred[0]:.0f} kg")

# === MULTIPLE LINEAR REGRESSION ===
print("\n=== Multiple Linear Regression ===")
data = pd.DataFrame({
    'rainfall': [150, 200, 180, 250, 300, 190, 220, 280],
    'fertilizer': [40, 50, 45, 60, 70, 55, 65, 75],
    'temperature': [28, 30, 29, 27, 26, 28, 27, 25],
    'yield': [2200, 2600, 2400, 2900, 3200, 2700, 2850, 3100]
})
X = data[['rainfall', 'fertilizer', 'temperature']]
y = data['yield']

# Scale features
X_scaled = scaler.fit_transform(X)

# Train model with Lasso regularization
model_multi = LassoCV(cv=3, random_state=42)
model_multi.fit(X_scaled, y)
print(f"Best alpha: {model_multi.alpha_}")
print("Feature Importance (Coefficients):")
for feature, coef in zip(X.columns, model_multi.coef_):
    print(f" {feature}: {coef:.2f}")

# Predict
new_conditions = [[230, 58, 27]]
new_conditions_scaled = scaler.transform(new_conditions)
prediction = model_multi.predict(new_conditions_scaled)
print(f"Predicted yield: {prediction[0]:.0f} kg/ha")

=== Simple Linear Regression ===
Best alpha: 1.0
Predicted yield at 55kg fertilizer: 2614 kg

=== Multiple Linear Regression ===
Best alpha: 0.3068689081443643
Feature Importance (Coefficients):
 rainfall: 157.48
 fertilizer: 206.80
 temperature: 53.93
Predicted yield: 2763 kg/ha


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [7]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train model
model = SVC(kernel='rbf', C=1, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [8]:
# Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define hyperparameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto'],
    'kernel': ['rbf', 'linear', 'poly']
}

# Initialize model and GridSearchCV
model = SVC(random_state=42)
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='accuracy')

# Perform hyperparameter tuning
grid_search.fit(X_train, y_train)

# Get best model and evaluate
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print("Best Parameters:", grid_search.best_params_)
print("Model Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Best Parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}
Model Accuracy: 0.9666666666666667
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
